### ISSUE TITLE
Keyboard Animations support

### ISSUE THREAD

**Issue by RONTheCookie** [Askannz/msi-perkeyrgb#11]
This would be quite nice to have for my friend, Askannz - do you know if the animations are built into the keyboard or if they are just software I could write that calls your tool?

He has the MSI GS65

**Comment by dfredell** [comment]
@RONTheCookie 
The animations are called presets. They are defined in software. It is a list of steps sent to the keyboard, and then it will cycle through the lists of colors.

See
```
  --list-presets        List available presets for the given laptop model.
  -p PRESET, --preset PRESET
                        Use vendor preset (see --list-presets).
```

Give it a try, it looks like GS65 should be supported https://github.com/Askannz/msi-perkeyrgb/blob/3cb90abeb4ea9c2c179a194a828abb9543fc264e/msi_perkeyrgb/msi_keyboard.py#L20

**Comment by RONTheCookie** [comment]
Thanks, I will have him test it when he can +1:
