### ISSUE TITLE
Kernel config

### ISSUE THREAD

**Issue by Ulrar** [Askannz/msi-perkeyrgb#15]
Hi,

Is there any kernel modules I should enable for this to work ? I've installed it from git and when I run the command with any preset I don't get an error, it just pauses for a second then returns without any output, but the keyboard's backlight remains off.

I have a GS65, the hidraw devices are in 666 and the fn key does turn the appropriate keys red, but that's the only time the backlighting turns on at all. I'm assuming there's some requirement in the kernel's .config but I'm not sure which

**Comment by Askannz** [comment]
Hi, sorry for the very late response.

This may sound like a stupid question, but are you sure the keyboard brightness is not turned down ? On my GE63 there are keyboard controls to adjust the brightness, and they completely override the software controls (msi-perkeyrgb can't do anything is the brightness is set to zero).

**Comment by Ulrar** [comment]
Yep, that's my bad then. I did try those controls but I must have tried the monitor ones I guess, which don't work. The other set of sunny keys do indeed bring the keyboard brightness up, and it does work fine.

Sorry for the noise then, thanks !

**Comment by apinunt** [comment]
MSI GE75 Raider 10SGS + ubuntu 20.04 Mate
I tried both sets of sunny keys to increase the brightness of the keyboard leds and neither worked.
Is there something else I need to do?
