### ISSUE TITLE
Working fine on a GT75 Archlinux

### ISSUE THREAD

**Issue by cyberconan** [Askannz/msi-perkeyrgb#18]
Using GS75 and everything ok after grant access to hdi0.
```
[karl@CyberPortatil ~]$ msi-perkeyrgb --model GS75 --list-presets
Available presets for GS75:
        - aqua
        - chakra
        - default
        - disco
        - drain
        - freeway
        - rainbow-split
        - roulette
[karl@CyberPortatil ~]$ msi-perkeyrgb --model GS75 -p aqua
```
Thanks a lot of!!
PD: Where can I find configuration files compatibles with your application?

**Comment by Askannz** [comment]
Thanks, added.

> PD: Where can I find configuration files compatibles with your application?

The current git version (going to be tagged as a proper release very soon) includes a couple of example files, and there are some in the README as well. But in the end, you have to write the configuration yourself.

I don't have time to write good pre-made configurations but if some are submtitted I'd be happy to add them to the repo.
