### ISSUE TITLE
Doesn't work with GE62

### ISSUE THREAD

**Issue by Sohimaster** [Askannz/msi-perkeyrgb#21]
I got such response 
![image](https://user-images.githubusercontent.com/16952035/66707016-f598a180-ed53-11e9-8bfd-5bee29dcefa0.png)

**Comment by ErrorErrorError** [comment]
Is your keyboard per key rgb?

**Comment by Askannz** [comment]
From the [pictures](https://www.techspot.com/review/1334-msi-ge62-7rd-apache/) it looks like your laptop keyboard has region-based (not per-key) RGB lighting. In that case msi-perkeyrgb won't work, you need something like [MSIKLM](https://github.com/Gibtnix/MSIKLM) instead.
