### ISSUE TITLE
Option to save current setting

### ISSUE THREAD

**Issue by miigotu** [Askannz/msi-perkeyrgb#40]
I set my keyboard up before I wrote linux over windows, and I dont really want to lose it. I do want to play around with this tool though. Is it possible to add a way to save the current config to a file?

**Comment by erikbdev** [comment]
> I set my keyboard up before I wrote linux over windows, and I dont really want to lose it. I do want to play around with this tool though. Is it possible to add a way to save the current config to a file?

I don't think there is a way to fetch the current data NVRAM from the keyboard, well at least when I tried doing it using macOS's version of `getFeatureReport`. Not sure if SteelSeries even uses that method to fetch the preset that is saved in the keyboard or writes it on the system.

**Comment by miigotu** [comment]
I'm not sure that is correct. The udev is marked with 0666 permissions (read and write), and the libhidapi-hidraw headers support reading afaik, so calling hid_get_feature_report rather than hid_send_feature_report should pull the config.

I'm currently a python developer, and previously an embedded c/c++ dev so I might take a look at getting this working.

The only way I see it potentially being an issue is using hidraw instead of libusb

https://github.com/signal11/hidapi/blob/master/hidapi/hidapi.h

**Comment by erikbdev** [comment]
> I'm currently a python developer, and previously an embedded c/c++ dev so I might take a look at getting this working.

Let me know too, since I am trying to get the feature report so I can show the current preset on my application `PrismUI`.

I've tried to use different `reportID` but it always returns zero.

**Comment by miigotu** [comment]
It will always return 0 unless you disable nonblocking mode. I don't think steel series has more than one report, so it might be 0x0 for the reportID.

I'll mess with it when I get to my laptop and let you know.

**Comment by miigotu** [comment]
@ErrorErrorError lol, now i think you might be right.


```python
[{'path': b'/dev/hidraw0', 'vendor_id': 4152, 'product_id': 4388, 'serial_number': '', 'release_number': 536,
  'manufacturer_string': 'SteelSeries', 'product_string': 'SteelSeries ALC', 'usage_page': 12080, 'usage': 12336,
  'interface_number': 0},
 {'path': b'/dev/hidraw1', 'vendor_id': 4152, 'product_id': 4388, 'serial_number': '', 'release_number': 536,
  'manufacturer_string': 'SteelSeries', 'product_string': 'SteelSeries ALC', 'usage_page': 0, 'usage': 0,
  'interface_number': 1},
 {'path': b'/dev/hidraw2', 'vendor_id': 4152, 'product_id': 4386, 'serial_number': '', 'release_number': 560,
  'manufacturer_string': 'SteelSeries', 'product_string': 'SteelSeries KLC', 'usage_page': 0, 'usage': 0,
  'interface_number': 0},
 {'path': b'/dev/hidraw3', 'vendor_id': 4152, 'product_id': 4386, 'serial_number': '', 'release_number': 560,
  'manufacturer_string': 'SteelSeries', 'product_string': 'SteelSeries KLC', 'usage_page': 0, 'usage': 0,
  'interface_number': 1}]
>>> zero = hid.Device(path=b'/dev/hidraw0')
>>> one = hid.Device(path=b'/dev/hidraw1')
>>> two = hid.Device(path=b'/dev/hidraw2')
>>> three = hid.Device(path=b'/dev/hidraw3')
>>> zero.nonblocking
0
>>> one.nonblocking
0
>>> two.nonblocking
0
>>> three.nonblocking
0
>>> for i in range(0, 256):
...     assert zero.get_feature_report(i, 256) == b'\x00' * 256, (i, zero)
...     assert one.get_feature_report(i, 256) == b'\x00' * 256, (i, one)
...     assert two.get_feature_report(i, 256) == b'\x00' * 256, (i, two)
...     assert three.get_feature_report(i, 256) == b'\x00' * 256, (i, three)
>>>
```

hidraw0 and hidraw1 are ALC (case lighting) and require root to access on my system, hidraw2 and hidraw3 are KLC (keyboard). None of theme return anything on any of the possible report ID's.

I wonder if a libusb hid library might be more effective?

**Comment by erikbdev** [comment]
> @ErrorErrorError lol, now i think you might be right.
> 
> 
> 
> 
> 
> ```python
> 
> [{'path': b'/dev/hidraw0', 'vendor_id': 4152, 'product_id': 4388, 'serial_number': '', 'release_number': 536,
> 
>   'manufacturer_string': 'SteelSeries', 'product_string': 'SteelSeries ALC', 'usage_page': 12080, 'usage': 12336,
> 
>   'interface_number': 0},
> 
>  {'path': b'/dev/hidraw1', 'vendor_id': 4152, 'product_id': 4388, 'serial_number': '', 'release_number': 536,
> 
>   'manufacturer_string': 'SteelSeries', 'product_string': 'SteelSeries ALC', 'usage_page': 0, 'usage': 0,
> 
>   'interface_number': 1},
> 
>  {'path': b'/dev/hidraw2', 'vendor_id': 4152, 'product_id': 4386, 'serial_number': '', 'release_number': 560,
> 
>   'manufacturer_string': 'SteelSeries', 'product_string': 'SteelSeries KLC', 'usage_page': 0, 'usage': 0,
> 
>   'interface_number': 0},
> 
>  {'path': b'/dev/hidraw3', 'vendor_id': 4152, 'product_id': 4386, 'serial_number': '', 'release_number': 560,
> 
>   'manufacturer_string': 'SteelSeries', 'product_string': 'SteelSeries KLC', 'usage_page': 0, 'usage': 0,
> 
>   'interface_number': 1}]
> 
> >>> zero = hid.Device(path=b'/dev/hidraw0')
> 
> >>> one = hid.Device(path=b'/dev/hidraw1')
> 
> >>> two = hid.Device(path=b'/dev/hidraw2')
> 
> >>> three = hid.Device(path=b'/dev/hidraw3')
> 
> >>> zero.nonblocking
> 
> 0
> 
> >>> one.nonblocking
> 
> 0
> 
> >>> two.nonblocking
> 
> 0
> 
> >>> three.nonblocking
> 
> 0
> 
> >>> for i in range(0, 256):
> 
> ...     assert zero.get_feature_report(i, 256) == b'\x00' * 256, (i, zero)
> 
> ...     assert one.get_feature_report(i, 256) == b'\x00' * 256, (i, one)
> 
> ...     assert two.get_feature_report(i, 256) == b'\x00' * 256, (i, two)
> 
> ...     assert three.get_feature_report(i, 256) == b'\x00' * 256, (i, three)
> 
> >>>
> 
> ```
> 
> 
> 
> hidraw0 and hidraw1 are ALC (case lighting) and require root to access on my system, hidraw2 and hidraw3 are KLC (keyboard). None of theme return anything on any of the possible report ID's.
> 
> 
> 
> I wonder if a libusb hid library might be more effective?

You could try it but I doubt it will be effective since steelseries might not have implemented `reportID` for get_feature_report. I don't even see SteelSeries Cliemt app requesting for information when using wire shark.
