### ISSUE TITLE
Mystic Light

### ISSUE THREAD

**Issue by akzytr** [Askannz/msi-perkeyrgb#57]
Hi, 

This is not really an issue, I just wanted to give a heads up that the project is compatibile with msi mystic light{the rgb header on laptops infront)

I have tested on my msi raider ge66:

Here is how i got it to work:

```
msi-perkeyrgb --id 1038:113c  {commands here}
``` 

the ID part is the output of lsusb:

```
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 004: ID 1038:113a SteelSeries ApS SteelSeries KLC
Bus 003 Device 003: ID 1038:113c SteelSeries ApS SteelSeries ALC
Bus 003 Device 005: ID 8087:0033 Intel Corp.
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

Here you can see that there are 2 devices - Steel Series KLC and ALC, I believe the KLC is the keyboard, since when i supply KLC as the id it changes my keyboard, but when I supply the ALC id, it applies those settings, but to the mystic light header instead.

I think you may want to update your project description and mention that it works with mystic light as well.

**Comment by cyrusbehr** [comment]
Thank you for this! I have been searching for a way for ages to turn of the LED bar on my GE66 running Ubuntu 22.04.

Output of lsusb:

```
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 1038:1122 SteelSeries ApS SteelSeries KLC
Bus 001 Device 006: ID 8087:0032 Intel Corp. AX210 Bluetooth
Bus 001 Device 005: ID 5986:1160 Acer, Inc Integrated Camera
Bus 001 Device 004: ID 1038:1132 SteelSeries ApS SteelSeries ALC
Bus 001 Device 002: ID 062a:4101 MosArt Semiconductor Corp. Wireless Keyboard/Mouse
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

```

I then ran: `sudo msi-perkeyrgb --id 1038:1132 -d`

It disabled 90 percent of the lightbar, except for 10% at the left side. 

Any idea how I can disable the entire lightbar? 

It seems GE66 is not recognized so it defaults to GE63, could this be why? 

`No laptop model specified, using GE63 as default.`
