### ISSUE TITLE
No package metadata was found for msi-perkeyrgb after updating Manjaro Linux

### ISSUE THREAD

**Issue by kevinveenbirkenbach** [Askannz/msi-perkeyrgb#58]
After I updated Manjaro Linux via sudo ```pacman -Syyu```, I get the follwowing error:
```bash
msi-perkeyrgb --model GS65 -s "ffffff" --id "1038:113a"                                                                                                                                PIPE ✘  59s  
Traceback (most recent call last):
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/msi-perkeyrgb", line 33, in <module>
    sys.exit(load_entry_point('msi-perkeyrgb==2.1', 'console_scripts', 'msi-perkeyrgb')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/msi-perkeyrgb", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for msi-perkeyrgb
```

**Comment by kve1989** [comment]
> After I updated Manjaro Linux via sudo `pacman -Syyu`, I get the follwowing error:
> 
> ```shell
> msi-perkeyrgb --model GS65 -s "ffffff" --id "1038:113a"                                                                                                                                PIPE ✘  59s  
> Traceback (most recent call last):
>   File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
>     return next(cls.discover(name=name))
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> StopIteration
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/bin/msi-perkeyrgb", line 33, in <module>
>     sys.exit(load_entry_point('msi-perkeyrgb==2.1', 'console_scripts', 'msi-perkeyrgb')())
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/bin/msi-perkeyrgb", line 22, in importlib_load_entry_point
>     for entry_point in distribution(dist_name).entry_points
>                        ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
>     return Distribution.from_name(distribution_name)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
>     raise PackageNotFoundError(name)
> importlib.metadata.PackageNotFoundError: No package metadata was found for msi-perkeyrgb
> ```

Hi. Do you got the problem solved?

**Comment by NourCheriff** [comment]
Hello! This issue remains unresolved, even though it has been open for over 9 months. 
To address it, consider rebuilding the package. If you’re using `yay`, you can execute the following command: `yay -S msi-perkeyrgb`.

**Comment by kevinveenbirkenbach** [comment]
> Hello! This issue remains unresolved, even though it has been open for over 9 months. To address it, consider rebuilding the package. If you’re using `yay`, you can execute the following command: `yay -S msi-perkeyrgb`.

Solved the issue
